language: rust
sudo: false

addons:
  apt:
    packages:
    - libasound2-dev

os:
  - linux
  - osx

env:
  global:
    - secure: "ZGNi7bKoxNIziWzdNP1QbH6ZbeWDInq42yq1rzWY71I/pi8yA4zjVAYdgXKElc0saB0d2TxJCwpeGVyXwuXXeNoud8HWsqQxhNVMM8K27a2jeezza8UCCJ7kAS6E/+gQj7w+HFtgWiUHZ0KEjGONqXJM+cWqH5oprTEuNBOPqDA="
    - secure: "H7JRHaCkm6NvmMU76pNUyK5fj8d0kEb1snGCTcC4ZdW98P5qSEDbMBOKZgSW0DNhKmzYS1qHHAXlmm9c9JCVYfeErL9JeTrRk4DvIO8sH3ImhHIB/q4U+h+hxZ6W+dGpTi0kjQ5ZS3z+Mlr/9CB4UT83HmF78Zfyf6KA15esUIQ="

after_success:
    - |
        [ $TRAVIS_BRANCH = master ] &&
        [ $TRAVIS_PULL_REQUEST = false ] &&
        cargo publish --token ${CRATESIO_TOKEN} --manifest-path alsa-sys/Cargo.toml
    - |
        [ $TRAVIS_BRANCH = master ] &&
        [ $TRAVIS_PULL_REQUEST = false ] &&
        cargo publish --token ${CRATESIO_TOKEN}
